### ISSUE TITLE
freeipa docker not working, start error is " FreeIPA server configuration failed"

### ISSUE THREAD

**Issue by robertchen** [freeipa/freeipa-container#192]
## my docker-compose file is as below:
```
version: '3'
services:
  freeipa:
    image: freeipa/freeipa-server:fedora-25
    container_name: freeipa-server
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      IPA_SERVER_HOSTNAME: "freeipaclone.sit.mycompany.io"
      IPA_SERVER_IP: 10.8.8.249
      TZ: America/Toronto
      ADMIN-PASSWORD: "admin12345"
      PASSWORD: "admin12345"
      DS-PASSWORD: "admin12345"
    volumes:
      - freeipa-data2:/data
      - /dev/urandom:/dev/random
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - 53:53/udp
      - 53:53
      - 80:80
      - 88:88
      - 88:88/udp
      - 389:389
      - 443:443
      - 464:464
      - 464:464/udp
      - 636:636
      - 7389:7389
      - 9443:9443
      - 9444:9444
      - 9445:9445
    hostname: "freeipaclone.sit.mycompany.io"
    tmpfs:
      - /run
      - /tmp

volumes:
  freeipa-data2:
```

## the docker-compose up -d with error:
```
To accept the default shown in brackets, press the Enter key.

Do you want to configure integrated DNS (BIND)? [no]:
Enter the fully qualified domain name of the computer
on which you're setting up server software. Using the form
<hostname>.<domainname>
Example: master.example.com.


Server host name [freeipaclone.sit.mycompnay.io]:
The domain name has been determined based on the host name.

Please confirm the domain name [sit.mycompnay.io]:
The kerberos protocol requires a Realm name to be defined.
This is typically the domain name converted to uppercase.

Please provide a realm name [SIT.mycompnay.IO]:
The IPA Master Server will be configured with:
Hostname:       freeipaclone.sit.mycompnay.io
IP address(es): 172.19.0.2
Domain name:    sit.mycompnay.io
Realm name:     SIT.mycompnay.IO

Continue to configure the system with these values? [no]: FreeIPA server configuration failed.
```
