### ISSUE TITLE
CRITICAL Failed to configure CA instance: returned non-zero exit status 1 

### ISSUE THREAD

**Issue by Piping** [freeipa/freeipa-container#193]
Hi,

I try to use the docker-compose to setup the freeipa. 

However, I encountered the configure CA error and it seems related to create CS.cfg file. But when I run it with docker run command it works.

Here is the docker-compose file I used:
```
version: '3'
services:
  freeipa:
    image: freeipa/freeipa-server:fedora-26
    container_name: freeipa-server
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      IPA_SERVER_IP: "110.10.100.100"
      IPA_SERVER_INSTALL_OPTS: "-U"
    volumes:
      - /freeipa:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - 53:53
      - 80:80
      - 88:88
      - 88:88/udp
      - 389:389
      - 443:443
      - 464:464
      - 464:464/udp
      - 636:636
      - 7389:7389
      - 9443:9443
      - 9444:9444
      - 9445:9445
    hostname: "ipa.example.com"
    tmpfs:
      - /run
      - /tmp

```
Here is the docker cmd I used:
```
docker run --name freeipa-server-container -e IPA_SERVER_IP=110.10.100.100 -p 53:53/udp -p 53:53   -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 \
-p 88:88/udp -p 464:464/udp -p 123:123/udp -p 7389:7389 \
-p 9443:9443 -p 9444:9444 -p 9445:9445 \
-ti -h ipa.example.com -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /freepia:/data:Z freeipa/freeipa-server:fedora-26

```

Here is the error message
```
freeipa-server |   [2/31]: configuring certificate server instance
freeipa-server |   [error] RuntimeError: CA configuration failed.
```

** Can you help me to understand the certificate system here? Is it possible to use letsencrypt as my external CA?**
