### ISSUE TITLE
Question: Is there  a working Docker file for Centos 7 without the need for using SYS_ADMIN capability ?? 

### ISSUE THREAD

**Issue by hawriRasch** [freeipa/freeipa-container#194]
Hi Guys,
I have been trying to create a freeipa container based on centos7 without success.
I encountered at least two, known, issues:
1- related to mounting folders (access denied)
2- related to enabled ipv6 ( no ip adress assigned to ::1)

due to security requirements, I have to avoid the use of SYS_ADMIN capability. 
To solve the second problem, there a patch, which is not available for Centos7, as I understand (please see: https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/thread/SEJEDA2IVWFPFRAGHH4MRBO6CUSGX3ZN/).

Would you please give me an advice.
 
Best Regards
Hawri

**Comment by hawriRasch** [comment]
I wonder if anybody has managed to run freeipa in a centos7 based container.

**Comment by Tiboris** [comment]
Hello @hawriRasch 
I will have a look into it ASAP.

**Comment by stlaz** [comment]
Hey.
I just tested the current CentOS Dockerfile in this repo and was able to run it only with SYS_TIME capability.
Not sure what your problem is with mounting folders, but if SELinux is the problem, you can just add `:Z` to the bind-mounted volume and that should fix that problem.
As for the other problem, I checked my running FreeIPA CentOS image and it indeed seems that the fix did not land in CentOS yet.

**Comment by hawriRasch** [comment]
Thanks @Slaznik for your answer.
The SYS_ADMIN capability is needed by sytemd to perform mounting operations. You can see a description of the problem here : https://github.com/systemd/systemd/issues/8657.
The question is about what should be used as docker cgroup driver: cgroupfs or systemd (pease see https://github.com/coreos/bugs/issues/1435.
I've tested the use of SYS_TIME, but it didn't help the problem .

Regarding the second issue: support for ipv6.
I have used the python patches, the fix mentioned here:  https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/thread/SEJEDA2IVWFPFRAGHH4MRBO6CUSGX3ZN/)
but they don't seem to solve the problem.

The solution is to activate the support for ipv6 in the container, which can be done by the use of this option:  --sysctl net.ipv6.conf.all.disable_ipv6=0, in docker run.

My conclusion is: in order to run freeipa in a centos7-based the following  steps need to be performed:

1- update Dockerfile as described here: https://hub.docker.com/_/centos/
2- Add options : --sysctl net.ipv6.conf.all.disable_ipv6=0 --cap-add=SYS_ADMIN to "docker run"

Kind Regards

**Comment by hawriRasch** [comment]
Hi @slaznik,

sorry for this delay. Yes I did. I haven't yet tested your version but managed to run the container by adding SYS_ADMIN capability and support for ipv6 to the container.
Thanks fot your support

**Comment by PhilipSchmid** [comment]
@hawriRasch What are the required change to enable "support for ipv6 to the container"?

Thanks

Regards,
Philip

**Comment by adelton** [comment]
If you are hitting something like https://github.com/freeipa/freeipa-container/issues/185, `--ipv6` to docker daemon options or `"ipv6": true` to `daemon.json` should help.

Or `--sysctl net.ipv6.conf.all.disable_ipv6=0` as mentioned in https://github.com/freeipa/freeipa-container/issues/194#issuecomment-384541844.

**Comment by PhilipSchmid** [comment]
Hi @adelton, thanks for the information. 

I was now able to get it running using the following settings:

Ensure the IPv6 stack is enabled on VM level:
```bash
[root@freeipa freeipa]# lsmod | grep ipv6
nf_reject_ipv6         13717  1 ip6t_REJECT
nf_conntrack_ipv6      18935  17
nf_defrag_ipv6         35104  1 nf_conntrack_ipv6
nf_nat_ipv6            14131  1 ip6table_nat
nf_nat                 26787  3 nf_nat_ipv4,nf_nat_ipv6,nf_nat_masquerade_ipv4
nf_conntrack          133053  8 nf_nat,nf_nat_ipv4,nf_nat_ipv6,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_netlink,nf_conntrack_ipv4,nf_conntrack_ipv6
```

Enable IPv6 at sysctl level for all interfaces except ens33 and esn34:
```bash
[root@freeipa freeipa]# cat /etc/sysctl.conf | grep net.ipv6.conf.
net.ipv6.conf.all.disable_ipv6=0
net.ipv6.conf.ens33.disable_ipv6=1
net.ipv6.conf.ens34.disable_ipv6=1
[root@freeipa freeipa]# sysctl -p
```

Enable IPv6 on the `lo` VM interface:
```bash
[root@freeipa freeipa]# cat /etc/sysconfig/network-scripts/ifcfg-lo  | grep IPV6
IPV6INIT=yes
IPV6ADDR=::1/128
[root@freeipa freeipa]# systemctl restart network
```

I'm using the following `docker-compose.yml` file:
```yml
version: "3.6"

services:
  server:
    image: index.docker.io/freeipa/freeipa-server:centos-7
    hostname: ipa.example.com
    domainname: example.com
    restart: always
    environment:
      TZ: Europe/Zurich
      IPA_SERVER_IP: 192.168.1.20
      #DEBUG_TRACE: 1
      #DEBUG_NO_EXIT: 1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - type: volume
        source: ipa-data
        target: /data
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /tmp
    network_mode: host
    ports:
      # FreeIPA WebUI
      - "80:80"
      - "443:443"
      # Kerberos
      - "88:88/udp"
      - "88:88"
      - "464:464/udp"
      - "464:464"
      # LDAP
      - "389:389"
      - "636:636"
      # DNS
      #- "53:53/udp"
      #- "53:53"
      # NTP
      #- "123:123/udp"
    extra_hosts:
      - "ipa.example.com ipa:192.168.1.10"
      - "localhost:127.0.0.1"
      - "lo:::1"
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: 'true'
        fluentd-buffer-limit: 100MB
        fluentd-max-retries: '30'
        fluentd-address: fluentd.example.com:24224

volumes:
  ipa-data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.1.5,nolock,soft,rw"
      device: ":/nfs/docker_volumes/ipa/data"
```

Regards,
Philip
