### ISSUE TITLE
Can't start container based on centos-7

### ISSUE THREAD

**Issue by rojopolis** [freeipa/freeipa-container#263]
I can't get a container based on the Centos 7 build from Dockerhub to start.

```IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add ::1 address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.```

Is there an easy way to work around this?

**Comment by adelton** [comment]
Try adding `--sysctl net.ipv6.conf.all.disable_ipv6=0` option to your `docker run` parameters.

**Comment by adelton** [comment]
Let me assume that this fixed the problem that you were hitting.

**Comment by paulcalabro** [comment]
@adelton I'm getting this same error while using Docker Swarm? According to this bug "Docker swarm does not enable ipv6 networking". However, the no matter what I set on the host, the container always shows IPv6 enabled, so there's an incompatibility. Is there a way to work around this?

**Comment by adelton** [comment]
I'm not aware of any, especially if you cannot pass that `--sysctl net.ipv6.conf.all.disable_ipv6=0` to docker swarm.

**Comment by paulcalabro** [comment]
Thanks for confirming. Unfortunately, that flag is not supported atm, however, it appears it's being added soon according to some GH activity I've seen. I did manage to workaround this, however, by commenting out one line in the Python code that does an IPv6 check and then removing the IPv6 related host entries. So if anyone else is wondering "is this possible with Docker Swarm?", I can confirm it is.

**Comment by paulcalabro** [comment]
Here's some more notes to assist anyone else doing this with Docker Swarm:

_docker-compose.yml_:

```
  freeipa_server-<REDACTED>:
    configs:
      -
        source: freeipa-install.py-v2019.03.07.07
        target: /usr/lib/python2.7/site-packages/ipaserver/install/server/install.py
      -
        source: freeipa-ipa_server_install_options-v2019.03.07.01
        target: /data/ipa-server-install-options
      -
        mode: 0550
        source: freeipa-rc.local-v2019.03.07.05
        target: /etc/rc.d/rc.local
    deploy:
      placement:
        constraints:
          - "node.labels.FreeIPA_Role == Server"
          - "node.labels.Subnet == <REDACTED>"
    entrypoint: /etc/rc.d/rc.local
    environment:
      - DEBUG_NO_EXIT=true
      - DEBUG_TRACE=true
    hostname: <REDACTED>
    image: "$DOCKER_REGISTRY/<REDACTED>/freeipa-server:centos-7"
    networks:
      backend:
        aliases:
          - <REDACTED>
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "freeipa_server_data:/data:Z"
```

_install.py_:

```
...
#tasks.check_ipv6_stack_enabled()
...
```

_/etc/rc.d/rc.local_:

```
#!/bin/bash
# THIS FILE IS ADDED FOR COMPATIBILITY PURPOSES
#
# It is highly advisable to create own systemd services or udev rules
# to run scripts during boot instead of using this file.
#
# In contrast to previous versions due to parallel execution during boot
# this script will NOT be run after all other services.
#
# Please note that you must run 'chmod +x /etc/rc.d/rc.local' to ensure
# that this script will be executed during boot.

touch /var/lock/subsys/local

# Update the hosts file content without changing its inode.
egrep -v 'ip6' /etc/hosts >/etc/hosts.new
cp /etc/hosts.new /etc/hosts

# Excute init.
/usr/local/sbin/init
```
