### ISSUE TITLE
Error  "too many redirects" while deploying on kubernetes

### ISSUE THREAD

**Issue by dharmendrakariya** [freeipa/freeipa-container#370]
I have deployed freeipa stack using [this created helm-chart](https://github.com/dharmendrakariya/freeipa-helm-chart).
but when I set ingress, browser keeps giving me error, regarding "too many redirects".

**Comment by adelton** [comment]
Please debug with `curl -Li` to see where those redirects point.

**Comment by dharmendrakariya** [comment]
I resolved it by disabling the rewrite rules, as per [this article](https://www.adelton.com/freeipa/freeipa-behind-ssl-proxy).

however, is there any way I can enable/disable it by help of some ENV or something. actually I am running this on K8S. So I want some fine defined method to disable it, rather than going into pod and disabling it manually.

**Comment by adelton** [comment]
The easiest way is probably to add your customization directly to the Dockerfile.

**Comment by dharmendrakariya** [comment]
> The easiest way is probably to add your customization directly to the Dockerfile.

I tried with the help of [dockerize](https://github.com/powerman/dockerize), but at run time when http server is being configured, the our placed file is being overwritten, I tried with immutable file also but that fails to configure http server and hence the freeipa installation fails. 

could you suggest how can I add customized one in docker directly? because http is being configured at runtime not build time. so hope you get it.

**Comment by adelton** [comment]
The `/etc/httpd/conf.d/ipa-rewrite.conf` is generated from `/usr/share/ipa/ipa-rewrite.conf.template` so the easiest way might be to patch that file in the image.

**Comment by dharmendrakariya** [comment]
and that is out of my scope i guess, coz I really don't know how to do that I mean the code level change and patch and all. but anyway, thanks for the help.

**Comment by gianlazz** [comment]
@dharmendrakariya The following may work by overwriting the `/usr/share/ipa/ipa-rewrite.conf.template` on deployment. This is the approach I've taken with the same problem when deploying nextcloud in k8s behind an external reverse proxy.

```yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeipa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeipa
  template:
    metadata:
      labels:
        app: freeipa
    spec:
      containers:
        - name: freeipa
          image: freeipa/freeipa-server:fedora-30
          env:
          - name: IPA_SERVER_HOSTNAME
            value: ipa.homelab.lazz.tech
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: freeipa
                key: admin.password
          - name: IPA_SERVER_INSTALL_OPTS
            value: "-U -r LAZZ.TECH --setup-dns --no-forwarders --no-ntp"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "100m"
            limits:
              memory: "1200Mi"
              cpu: "500m"
          # readinessProbe:
          #   exec:
          #     command: [ "/usr/bin/systemctl", "status", "ipa" ]
          #   initialDelaySeconds: 60
          #   timeoutSeconds: 10
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          - containerPort: 53
            protocol: UDP
          - containerPort: 88
            protocol: TCP
          - containerPort: 88
            protocol: UDP
          volumeMounts:
          - mountPath: /data
            name: freeipa-data
          - name: cgroups
            mountPath: /sys/fs/cgroup
            readOnly: true
          - mountPath: /usr/share/ipa/ipa-rewrite.conf.template
            name: freeipa-httpd-config
            subPath: ipa-rewrite.conf.template
          imagePullPolicy: IfNotPresent
      volumes:
      - name: freeipa-data
        hostPath:
          # directory location on host
          path: /opt/freeipa
          type: DirectoryOrCreate
      - name: cgroups
        hostPath:
          path: /sys/fs/cgroup
      - name: freeipa-httpd-config
        configMap:
            name: freeipa-httpd-config
            items:
              - key: default
                path: default
---
apiVersion: v1
kind: Service
metadata:
  name: freeipa-service
spec:
  ports:
  - port: 80
    targetPort: 80
    name: tcp
  selector:
    app: freeipa
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: freeipa-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: ipa.homelab.lazz.tech
    http:
      paths:
      - backend:
          serviceName: freeipa-service
          servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: freeipa-httpd-config
data:
  ipa-rewrite.conf.template: |
    # VERSION 6 - DO NOT REMOVE THIS LINE

    RewriteEngine on

    # By default forward all requests to /ipa. If you don't want IPA
    # to be the default on your web server comment this line out.
    ${AUTOREDIR}RewriteRule ^/$$ https://$FQDN/ipa/ui [L,NC,R=301]

    # Redirect to the fully-qualified hostname. Not redirecting to secure
    # port so configuration files can be retrieved without requiring SSL.
    RewriteCond %{HTTP_HOST}    !^$FQDN$$ [NC]
    RewriteRule ^/ipa/(.*)      http://$FQDN/ipa/$$1 [L,R=301]

    # Redirect to the secure port if not displaying an error or retrieving
    # configuration.
    #
    # THESE LINES SHOULD BE COMMENTED OUT TO AVOID INFINITE REDIRECT BEHIND
    # EXTERNAL SSL REVERSE PROXY
    #
    # RewriteCond %{SERVER_PORT}  !^443$$
    # RewriteCond %{REQUEST_URI}  !^/ipa/(errors|config|crl)
    # RewriteCond %{REQUEST_URI}  !^/ipa/[^\?]+(\.js|\.css|\.png|\.gif|\.ico|\.woff|\.svg|\.ttf|\.eot)$$
    # RewriteRule ^/ipa/(.*)      https://$FQDN/ipa/$$1 [L,R=301,NC]

    # Rewrite for plugin index, make it like it's a static file
    RewriteRule ^/ipa/ui/js/freeipa/plugins.js$$    /ipa/wsgi/plugins.py [PT]
```
