### ISSUE TITLE
FreeIPA DNS Resolution Starts Failing After Restart

### ISSUE THREAD

**Issue by mattjamesaus** [freeipa/freeipa-container#380]
When running this container in docker on AWS ,with the following setup, using ansible - but it should be pretty self explanatory what it's doing here. Running the containers on separate hosts not using swarm or anything like that i'm seeing that both the master and replica work great however upon a restart of the containers they lose the ability to communicate with one another. It looks like during the restart of the container the /etc/resolv.conf gets overwritten to only contain
`nameserver 127.0.0.1`
where previously when it's working that has the route53 ip address, what i'm trying to figure is if:
a) I'm missing some underlying setup configuration 
b) Running this in an unorthodox setup
c) There is a subtle bug in ipa-server-configure-first

```
 community.general.docker_container:
    name: freeipa
    image: freeipa/freeipa-server:centos-8
    command :
      - "ipa-server-install"
    env:
      IPA_SERVER_IP: "{{ ansible_default_ipv4.address }}"
      SERVER_IP_ADDRESS: "{{ ansible_default_ipv4.address }}"
    state: started
    read_only: yes
    recreate: yes
    hostname: "{{ inventory_hostname }}"
    ports:
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "80:80/udp"
      - "464:464/udp"
    restart_policy: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - /var/lib/ipa-data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
```
```
  community.general.docker_container:
    name: freeipa
    image: freeipa/freeipa-server:centos-8
    command:
      -  "ipa-replica-install"
    env:
      IPA_SERVER_IP: "{{ ansible_default_ipv4.address  }}"
      SERVER_IP_ADDRESS: "{{ ansible_default_ipv4.address  }}"
    state: started
    read_only: yes
    recreate: yes
    restart_policy: always
    hostname: "{{ inventory_hostname }}"
    ports:
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "80:80/udp"
      - "464:464/udp"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - /var/lib/ipa-data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
```

it looks like i'll be able to fix it pretty simply by just adding an ENV to the container to add an additional DNS to the resolv.conf but that doesn't seem like the right approach here. To clarify i don't want to use freeIPA's DNS features and instead rely on route53 to do it but no combination of settings i can come up with makes this work.

The fix i've currently attempting is changing ipa-server-configure-first to
```
	if [ -f /data/etc/resolv.conf.ipa ] && ! grep '^nameserver 127\.0\.0\.1$' /etc/resolv.conf ; then
		perl -pe 's/^(nameserver).*/$1 127.0.0.1/' /data/etc/resolv.conf.ipa > /etc/resolv.conf
		if ! grep -q "\b$HOSTNAME\b" /etc/hosts ; then
			echo "127.0.0.2 $HOSTNAME" >> /etc/hosts
		fi
		if [[ -z "${EXTERNAL_DNS_RESOLVER}" ]]; then
      	echo "No External DNS Address Set Skipping"
    else
      	echo "nameserver $EXTERNAL_DNS_RESOLVER" >> /etc/resolv.conf
    fi
	fi
```
