### ISSUE TITLE
Password with Two Dollar Signs Not Working

### ISSUE THREAD

**Issue by ccravens** [freeipa/freeipa-container#401]
I'm deploying FreeIPA docker container in a k8s cluster. When I pass it a password with two $$ in a row it seems to not work, however, when I change the second dollar sign ($) to something else, I can login. For example:

`T)T}Bjxl&@s$$z!&UJN(e#cNE5cimmX%` << DOES NOT WORK
`T)T}Bjxl&@s$Az!&UJN(e#cNE5cimmX%` << WORKS
                         ^-- changing this from $ to A I can now login

`AaAaAaAaAaA$$AaAaAaAaAaAaAaAaAaA` << DOES NOT WORK
`AaAaAaAaAaAa$AaAaAaAaAaAaAaAaAaA` << WORKS
                          ^-- changing this from $ to a I can now login

These are the env vars I'm passing to the container from the k8s manifest yaml:

```yaml
      - env:
        - name: IPA_SERVER_HOSTNAME
          value: a.ipa.namespace.svc.cluster.local
        - name: PASSWORD
          value: T)T}Bjxl&@s$$z!&UJN(e#cNE5cimmX%
        - name: IPA_SERVER_INSTALL_OPTS
          value: --unattended --realm=CLUSTER.LOCAL --admin-password='T)T}Bjxl&@s$$z!&UJN(e#cNE5cimmX%'
            --ds-password='i&MTuQpt(pvnmynV12|o@#oFixZ{@9L9' --master-password='!LyLQ7&%]JF[*!SmZ#vG0(9tmiTnXqE#'
            --no-ntp --no_hbac_allow --no-ssh --no-sshd --debug
```

Note: These passwords are NOT being used in any system and are just being provided as specific examples of behavior I'm seeing when standing up a FreeIPA container
