### ISSUE TITLE
Replication healthchek failed after upgrade to centos8-4.9.2

### ISSUE THREAD

**Issue by alexandrovas** [freeipa/freeipa-container#409]
Hello!
I have errors after upgrade to centos8-4.9.2:
```
ipa-healthcheck --failures-only
...
{
    "source": "ipahealthcheck.ds.replication",
    "check": "ReplicationCheck",
    "result": "ERROR",
    "uuid": "194574b9-2394-45dc-aaea-abe992c6f2c3",
    "when": "20210701090308Z",
    "duration": "0.171359",
    "kw": {
      "key": "DSREPLLE0003",
      "items": [
        "Replication",
        "Agreement"
      ],
      "msg": "The replication agreement (metoipa01.prod-ins2.pcbl.local) under \"dc=pcbl,dc=local\" is not in synchronization.\nStatus message: error (1) can't acquire busy replica (unable to acquire replica: the replica is currently being updated by another supplier.)"
    }
  }
...
```

The error is not permanent, it appears and disappears on all replicas in my topology. I have script that starts by cron every 5 minutes and it parses ipa-healthcheck output.

My docker-compose.yml:

```yml
version: "3.5"

services:
  freeipa:
    image: freeipa/freeipa-server:centos-8-4.9.2
    container_name: freeipa
    restart: always
    network_mode: host
    hostname: ipa01.prod.pcbl.local
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./data:/data:Z
      - ./conf/ipa-options-ext.conf:/etc/named/ipa-options-ext.conf
      - ./conf/ipa-ext.conf:/etc/named/ipa-ext.conf
      - ./conf/rpz.zone:/etc/named/rpz/rpz.zone
      - ./conf/ipa_healthcheck:/etc/cron.d/ipa_healthcheck
      - ./conf/pki-log-clean:/etc/cron.d/pki-log-clean
      - ./conf/scripts:/scripts:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /dev/urandom:/dev/random:ro
      - /opt/node_exporter/metrics/freeipa.prom:/metrics/freeipa.prom
      - ./conf/chrony.conf:/etc/chrony.conf
    cap_add:
      - SYS_TIME
    tmpfs:
      - /run
      - /tmp
    environment:
      TZ: Europe/Moscow
      IPA_SERVER_HOSTNAME: ipa01.prod.pcbl.local
      IPA_SERVER_IP: 10.72.4.20
    extra_hosts:
      - "ipa01.prod.pcbl.local:10.72.4.20"
      - "ipa01:10.72.4.20"
```

In /var/log/dirsrv/slapd-PCBL-LOCAL/errors I see such messages:
```
[01/Jul/2021:08:59:34.206569590 +0000] - WARN - content-sync-plugin - sync_update_persist_betxn_pre_op - DB retried operation targets "fqdn=ed-gredis-01.prod.pcbl.local,cn=computers,cn=accounts,dc=pcbl,dc=local" (op=0x7f8e06900e00 idx_pl=0) => op not changed in PL
[01/Jul/2021:09:00:11.090972399 +0000] - WARN - content-sync-plugin - sync_update_persist_betxn_pre_op - DB retried operation targets "fqdn=ed-glob-db-03.prod.pcbl.local,cn=computers,cn=accounts,dc=pcbl,dc=local" (op=0x7f8e17224000 idx_pl=0) => op not changed in PL
[01/Jul/2021:09:00:11.161777148 +0000] - WARN - content-sync-plugin - sync_update_persist_betxn_pre_op - DB retried operation targets "fqdn=mgmt-efk-04.prod.pcbl.local,cn=computers,cn=accounts,dc=pcbl,dc=local" (op=0x7f8e30a24800 idx_pl=0) => op not changed in PL
[01/Jul/2021:09:00:14.083754313 +0000] - WARN - content-sync-plugin - sync_update_persist_betxn_pre_op - DB retried operation targets "fqdn=ed-mng-db-02.prod.pcbl.local,cn=computers,cn=accounts,dc=pcbl,dc=local" (op=0x7f8e0ac14e00 idx_pl=0) => op not changed in PL
[01/Jul/2021:09:10:22.097113649 +0000] - WARN - content-sync-plugin - sync_update_persist_betxn_pre_op - DB retried operation targets "dc=pcbl,dc=local" (op=0x7f8e18024c00 idx_pl=0) => op not changed in PL
```

This messages appears constantly for different LDAP targets.
