### ISSUE TITLE
Failed to create /init.scope control group: Read-only file system

### ISSUE THREAD

**Issue by FrozenSource** [freeipa/freeipa-container#410]
Hi guys,

Trying freeipa out through docker-compose though tried pretty much everything now including podman.

I have created this sample from the instructions on this repo and have also used many other configurations but I keep getting:
```
Failed to create /init.scope control group: Read-only file system
```

I am running the host on Fedora 34 with docker and the container_manage_cgroup bool enabled and SeLinux enforcing.
I tried privileged, without tmpfs, all capabilities with multiple combinations of those.
Is anybody able to help since I can't find any working solution either.

```
version: '3'

services:
  freeipa:
    image: freeipa/freeipa-server:fedora-rawhide
    container_name: ipa.*.nl
#    sysctls:
#      - net.ipv6.conf.all.disable_ipv6=1
    hostname: ipa.*.nl
#    read_only: true
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - DEBUG_TRACE=1
#      - IPA_SERVER_HOSTNAME=ipa.*.nl
    command:
      - --admin-password=*
      - --ds-password=*
      - --realm=*.nl
#      - --unattended
      - --domain=*.nl
    ports:
      # FreeIPA WebUI
      - "8080:80"
#      - "443:443"
      # Kerberos
#      - "88:88/udp"
#      - "88:88"
#      - "464:464/udp"
#      - "464:464"
      # LDAP
#      - "389:389"
#      - "636:636"
      # DNS
      # - "53:53/udp"
      # - "53:53"
      # NTP
#      - "123:123/udp"
      # other
#      - "7389:7389"
#      - "9443:9443"
#      - "9444:9444"
#      - "9445:9445"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - ./data:/data:Z # Z not really needed since I managed the permissions for this directory.
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - services
    cap_add:
      - SYS_ADMIN

networks:
  services:
    external: true
```
