### ISSUE TITLE
Docker run freeipa/freeipa-server:centos-8

### ISSUE THREAD

**Issue by anp135** [freeipa/freeipa-container#419]
Hello again -).

Follow to your propose for using centos-8 based image. I'm got fail again unfortunately -(.

So docker-compose.yml is:
```
version: '3.8'
services:
  ldap:
    image: freeipa/freeipa-server:centos-8
    restart: unless-stopped
    hostname: ...
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    labels:
      ...
    environment:
      - DEBUG_TRACE=1
      - DEBUG_NO_EXIT=1
      - HOSTNAME=ldap.dm.test.ru
      - NO_NTP=1
      - ADMIN_PASSWORD=secret123
      - DM_PASSWORD=secret123
      - DOMAIN_NAME=test.ru
      - REALM_NAME=TEST.RU
    command: "-U"
    volumes:
      - ./ldap:/var/lib/ldap
      - ./slapd:/etc/ldap/slapd.d
      - ./ssl:/container/service/slapd/assets/certs
      - ./data:/data
      - ./run:/run
```
Container image is freeipa/freeipa-server:centos-8 with image id e9d82b8c590d.

So now I have empty ipa-server-run.log and  ipa-server-configure-first.log with just one row:
`Fri Aug 20 07:33:46 UTC 2021 /usr/local/sbin/init -U`

The end of docker logs is:
```
+ echo 'Fri Aug 20 07:33:46 UTC 2021 /usr/local/sbin/init -U'
+ SHOW_LOG=1
+ '[' 1 == 1 ']'
+ for i in /var/log/ipa-server-configure-first.log /var/log/ipa-server-run.log
+ '[' -f /var/log/ipa-server-configure-first.log ']'
+ for i in /var/log/ipa-server-configure-first.log /var/log/ipa-server-run.log
+ '[' -f /var/log/ipa-server-run.log ']'
+ touch /var/log/ipa-server-run.log
+ trap '' SIGHUP
+ tail --silent -n 0 -f --retry /var/log/ipa-server-configure-first.log /var/log/ipa-server-run.log
+ '[' -n '' ']'
+ exec /usr/sbin/init --show-status=false
```

I tried run ipa-server-install in container directly via docker exec (with -ti -u root) and got next:
```
# ipa-server-install -N --realm=TEST.RU --domain=test.ru -U
Usage: ipa-server-install [options]

ipa-server-install: error: In unattended mode you need to provide at least -r, -p and -a options
The ipa-server-install command failed.
# ipa-server-install -N --realm=TEST.RU --domain=test.ru -U -p secret123 -a secret123

The log file for this installation can be found in /var/log/ipaserver-install.log
==============================================================================
This program will set up the IPA Server.
Version 4.9.2

This includes:
  * Configure a stand-alone CA (dogtag) for certificate management
  * Create and configure an instance of Directory Server
  * Create and configure a Kerberos Key Distribution Center (KDC)
  * Configure Apache (httpd)
  * Configure the KDC to enable PKINIT

Excluded by options:
  * Configure the NTP client (chronyd)


The IPA Master Server will be configured with:
Hostname:       ldap.dm.test.ru
IP address(es): 172.16.0.2
Domain name:    test.ru
Realm name:     TEST.RU

The CA will be configured with:
Subject DN:   CN=Certificate Authority,O= TEST.RU
Subject base: O= TEST.RU
Chaining:     self-signed

Disabled p11-kit-proxy
Configuring directory server (dirsrv). Estimated time: 30 seconds
  [1/41]: creating directory server instance
Failed to connect to bus: No such file or directory
  [error] CalledProcessError: Command '['systemctl', 'start', 'dirsrv@TEST-RU']' returned non-zero exit status 1.
Command '['systemctl', 'start', 'dirsrv@TEST-RU']' returned non-zero exit status 1.
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

```

The ipaserver-install.log attached
[ipaserver-install.log](https://github.com/freeipa/freeipa-container/files/7019935/ipaserver-install.log)

Thanks a lot for advice -).
