### ISSUE TITLE
Docker compose unattended installation

### ISSUE THREAD

**Issue by Maypul** [freeipa/freeipa-container#448]
Hi there,
I cannot seem to be able to start the automated installation with docker compose. I have not tried with docker run yet becase the ideal solution for me would be compose, even with setting the server up.

Here's my compose: [readable screen https://imgur.com/a/28d26NQ]
```
  freeipa:
    container_name: freeipa
    hostname: ipa.example.com
    image: freeipa/freeipa-server:centos-8-stream
    restart: unless-stopped
    privileged: false
    read_only: true
    command:
      - --realm=example.com #also tried putting it inside _server_install_options to cut out the command block or invoking "ipa-server-install -U" via this. Visible in log only currently only if run from command, not from the secret file
    networks:
      network:
        ipv4_address: 10.10.0.251
    ports:
      ## HTTP/HTTPS
      - 9442:80/tcp
      - 9443:443/tcp
      ## LDAP/LDAPS
      - 389:389/tcp
      - 636:636/tcp
      ## Kerberos
      - 88:88/tcp
      - 88:88/udp
      - 464:464/tcp
      - 464:464/udp
      ## DNS
      # - 53:53/tcp
      # - 53:53/udp
      ## NTP
      # - 123:123/udp
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKER/freeipa/data:/data:rw
      - $DOCKER/freeipa/journal:/var/log/journal:rw
      - $DOCKER/freeipa/run:/run:rw
      - $DOCKER/freeipa/tmp:/tmp:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro # tried with and without this
    secrets:
      - source: freeipa_server_install_options
        target: /data/ipa-server-install-options
    environment:
      IPA_SERVER_HOSTNAME: ipa.example.com
      IPA_SERVER_IP: 10.10.0.251
      DEBUG_TRACE: 1
      DEBUG_NO_EXIT: 1
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0`
```
No matter how I start this with compose, the container seems to start up and do nothing, web gui not loading.

Log from console
[_FreeIPA_logs.txt](https://github.com/freeipa/freeipa-container/files/8156262/_FreeIPA_logs.txt)

Content of `freeipa_server_install_options` secret:
```
--ds-password=password
--master-password=password
--admin-password=password
--idstart=0 # tried with or without
--idmax=0 # tried with or without
--no_hbac_allow # tried with or without
--no-ui-redirect # tried with or without
--U # tried with or without
```
Which seems to be working as if i copy the file from inside of the container I can see it's in here, I see no data only in the mounted directory, file is empty.

Is there something I have missed or it's just impossible to run from compose file? Based on comments I found around it seemed it was possible to set up similar war even if docker run is recommended which I will be probably forced to use.
