### ISSUE TITLE
Deployment on Kubernetes - no installation, no logs but some directories/files created

### ISSUE THREAD

**Issue by leonidas-o** [freeipa/freeipa-container#451]
Running on Kubernetes server: 1.18.5

I'm trying to deploy a single FreeIPA instance into a K8s cluster. Using ArgoCD for deployment and the "Kustomization" file structure.

I got the following file structure consumed by ArgoCD: 
- "freeipa"
    - "base"
        - "deployment.yaml"
        - "kustomization.yaml"
        - "pvc.yaml"
        - "service.yaml"
    - "overlay"
        - "tools"
            - "ambassador-mapping.yaml"
            - "deployment-patch.yaml"
            - "kustomization.yaml"

Files of interest are `deployment.yaml` and `deployment-patch.yaml`, therefore only these two listed here. I also tried with `readOnlyRootFilesystem=true` but with this flag, the pod is not even able to come up. It just shows `cp: cannot create regular file '/etc/hosts.dist': Read-only file system`
I saw some old issues in here using `Kind: Pod`, so I hope there is not anything deep down hidden, specific to deployments, which makes it impossible to run FreeIPA as a deployment?
I've got a PVC, which is working fine. The secrets are also setup and correctly resolved inside the container.

### deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeipa
  labels:
    app: freeipa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeipa
  template:
    metadata:
      labels:
        app: freeipa
    spec:
      containers:
        - name: freeipa
          image: freeipa/freeipa-server:rocky-8-4.9.6
          securityContext:
            readOnlyRootFilesystem: false
          imagePullPolicy: Always
          resources:
            limits:
              memory: 2048Mi
              cpu: 250m
            requests:
              memory: 2048Mi
              cpu: 150m
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: ldap
              containerPort: 389
              protocol: TCP
            - name: ldaps
              containerPort: 636
              protocol: TCP
            #- name: dns-tcp
            #  containerPort: 53
            #  protocol: TCP  
            #- name: dns-udp
            #  containerPort: 53
            #  protocol: UDP
            #- name: ntp
            #  containerPort: 123
            #  protocol: UDP
            - name: kerberos-tcp
              containerPort: 88
              protocol: TCP
            - name: kerberos-udp
              containerPort: 88
              protocol: UDP
            - name: kpasswd-tcp
              containerPort: 464
              protocol: TCP
            - name: kpasswd-udp
              containerPort: 464
              protocol: UDP
          volumeMounts:
            - mountPath: /data
              name: freeipa-volume
      volumes:
        - name:  freeipa-volume
          persistentVolumeClaim:
            claimName: freeipa-pvc
```

### deployment-patch.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeipa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: freeipa
          image: freeipa/freeipa-server:rocky-8-4.9.6
          env:
            - name: DS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freeipa-secrets
                  key: ds-password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freeipa-secrets
                  key: admin-password
            - name: IPA_SERVER_HOSTNAME
              value: freeipa.tools-in-my-namespace.svc.cluster.t10
            - name: IPA_SERVER_INSTALL_OPTS
              value: "-U -r CLUSTER.T10 --no-ntp --ds-password=$(DS_PASSWORD) --admin-password=$(ADMIN_PASSWORD)"
      serviceAccountName: MYSERVICEACCOUNT
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - IPADDRESS1
          - IPADDRESS2

```

After deploying, I've checked the freshly created pod, unfortunately there are no logs shown in ArgoCD's console which is already pretty strange. Never had such a behavior. Therefore I entered the container and checked the environment variables, all of them were setup correctly, also checked the `/data` directory plus some important paths mentioned in: https://www.freeipa.org/page/Troubleshooting/Installation

```
[root@freeipa-f5bcccff4-5xlbv /]# ls -lah /data/
total 36K
drwxr-xr-x.  8 root root 10 May  9 15:40 .
drwxr-xr-x.  1 root root 17 May  9 15:40 ..
drwxr-xr-x.  4 root root  4 May  4 04:51 .configfiles
drwxr-xr-x.  4 root root  4 May  4 04:51 .configfiles-noreplace
-rw-r--r--.  1 root root 37 May  4 04:51 build-id
drwxr-xr-x. 19 root root 23 May  4 04:50 etc
-rw-r--r--.  1 root root 46 May  9 15:40 hostname
drwxr-xr-x.  3 root root  3 May  4 04:50 root
drwxr-xr-x.  3 root root  3 May  4 04:50 usr
drwxr-xr-x.  6 root root  6 May  9 15:40 var
``` 

I somehow have the feeling, that the installation wasn't launched although the docs say: `The ipa-server-install command is the default and can be omitted.`.
```
[root@freeipa-f5bcccff4-5xlbv /]# ls -lah /data/var/log/
total 176K
drwxr-xr-x. 9 root root   14 May  9 15:40 .
drwxr-xr-x. 6 root root    6 May  9 15:40 ..
-rw-rw----. 1 root utmp    0 Mar 28 15:49 btmp
drwxr-xr-x. 2 root root    2 Mar 15 16:27 dirsrv
drwx------. 2 root root    2 Mar 24 17:34 httpd
drwxr-xr-x. 3 root root    3 May  4 04:50 ipa
-rw-r--r--. 1 root root   51 May  9 15:40 ipa-server-configure-first.log
-rw-r--r--. 1 root root    0 May  9 15:40 ipa-server-run.log
drwxr-xr-x. 2 root root    2 May  9 15:40 journal
-rw-rw-r--. 1 root utmp 112K May  4 04:50 lastlog
drwxr-xr-x. 2 root root    2 Apr 26 17:09 pki
drwx------. 3 root root    3 May  4 04:49 samba
drwxr-x---. 2 sssd sssd    2 Feb  1 21:07 sssd
-rw-rw-r--. 1 root utmp    0 Mar 28 15:49 wtmp
```

Also in here, completely empty.
```
[root@freeipa-f5bcccff4-5xlbv /]# ls -lah /data/var/log/pki/
total 8.0K
drwxr-xr-x. 2 root root  2 Apr 26 17:09 .
drwxr-xr-x. 9 root root 14 May  9 15:40 ..
```

I remember I had some issues when installing FreeIPA locally inside a VM when the FQDN was resolving to ::1 or 127.0.0.1 in /etc/hosts. So this is inside the container after the deployment. I don't know why k8s puts the same fqdn for the IP address, but I guess this shouldn't be a issue.
```
[root@freeipa-f5bcccff4-5xlbv /]# cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
100.xxx.xxx.xx  freeipa.tools-in-my-namespace.svc.cluster.t10 freeipa.tools-in-my-namespace.svc.cluster.t10. freeipa-f5bcccff4-5xlbv
```

Am I missing something in here? I don't understand why no logs are generated. Appreciate any help.

**Comment by adelton** [comment]
Should I venture a guess, I'd say that the systemd in the container does not start or fails very quickly after starting.

What's in that `/data/var/log/ipa-server-configure-first.log`?

What is the OS on the host? Are you sure you do not need to mount `/sys/fs/cgroups` to the container, similar to https://github.com/freeipa/freeipa-container/blob/master/tests/freeipa-k3s.yaml#L64-L66 and https://github.com/freeipa/freeipa-container/blob/master/tests/freeipa-k3s.yaml#L64-L66?

**Comment by leonidas-o** [comment]
@adelton Unfortunately the pod was already killed, so I can't look into `/data/var/log/ipa-server-configure-first.log`. But iirc it was either empty, or had just one line in there (that would explain the file size of "51"). For the OS, kubectl describe nodes gives me: `OS Image: CentOS Linux 7 (Core)`.

Very good point, after adding the mounts for `/sys/fs/cgroups` it finally gave me some log output:
```
IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add ::1 address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.     ││ The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information    
```

So I tried to add `sysctl` below the `readOnlyRootFilesystem` line inside the deployment file:
```
          securityContext:
            readOnlyRootFilesystem: false
            sysctls:
              - name: net.ipv6.conf.all.disable_ipv6
                value: "1"
```
But I get a `error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "sysctls" in io.k8s.api.core.v1.SecurityContext`. Looks like I had to talk to the cluster admin for that feature, in case you haven't got any other approach or useful hint to solve that?

**Comment by adelton** [comment]
> Looks like to posted the same link twice for the mount cgroups part, I guess one should be the volume mounts and the other the volume definition at the bottom?

Yes, I mispasted. I fixed it now.

If you got to the point that the installer complains about the IPv6 stack, that means systemd runs and `ipa-server-install` got started (and you should have output of that in `/data/var/log/ipaserver-install.log`.

I don't think I have any other hints WRT the sysctls in Kubernetes.

**Comment by leonidas-o** [comment]
A small update here, haven't tested it on the real cluster, need the cluster admin to add the unsafe-sysctls to the kubelet conf. But could reproduce it inside minikube and also get FreeIPA to fully run through the installation process.

So it is needed that your cluster admin either add this argument to the kubelet call:
```
kubelet --allowed-unsafe-sysctls \
  'net.ipv6.conf.lo.*' ...
```
OR as it seems that this is deprecated, lookup the path for your kubelet config file (it's listed after `--config` argument where the kubelet is called.) and add the sysctl command to it:
```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
allowedUnsafeSysctls:
- "net.ipv6.conf.lo.*"
```
> Don't forget to restart the kubelet

It is crucial that inside the deployment file, the `securityContext` is setup correctly. Beware, there can be multiple `securityContext` entries, one in `spec.template.spec` and one in ``spec.template.spec.containers`.
```yaml
...
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeipa
  template:
    metadata:
      labels:
        app: freeipa
    spec:
      securityContext:
        sysctls:
          - name: net.ipv6.conf.lo.disable_ipv6
            value: "0"
      containers:
        - name: freeipa
          image: freeipa/freeipa-server:rocky-8-4.9.6
          securityContext:
            readOnlyRootFilesystem: false
         ...
```
As stated FreeIPA installation was completely executed, seen in the logs, still have to be tested on the real cluster but I don't expect any issues there. I hope this helps the next one, who is deploying it into a k8s cluster.
