### ISSUE TITLE
web ui in kubernetes, running behind reverse proxy under subpath

### ISSUE THREAD

**Issue by leonidas-o** [freeipa/freeipa-container#452]
Running on Kubernetes server: 1.18.5

The auto installation looks good so far, see no errors and got the typical log message at the end inside `/data/var/log/ipa-server-configure-first.log`:
```
This program will set up IPA client.
Version 4.9.6

...
FreeIPA server configured.
```

In Kubernetes I'm using the following ambassador mapping:
```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: freeipa-ui
spec:
  host: tools.test.my.domain.com
  prefix: /subdir/freeipa/
  rewrite: /subdir/freeipa/ipa/ui/
  service: http://freeipa-ui:80
  ...
```

When looking at FreeIPA's pods `access_log` while trying to enter the web ui, I get the following 404 message.
`tail -f /data/var/log/httpd/access_log`
```
... [13/May/2022:09:15:29 +0000] "GET /subdir/freeipa/ipa/ui/ HTTP/1.1" 404 196 "-" "Mozilla/5.0 ...
```

So FreeIPA seems running fine, the ui should be reachable under `tools.test.my.domain.com/subdir/freeipa`, because there are other tools within this host, in their own sub dir. As I can see the access_log monitoring the requests, I would say the current ambassador mapping is also working, I'm reaching the webserver.
I guess I just have to tell FreeIPA that it is running behind reverse proxy under subpath different from `/`? So I need to change the baseHref/ basePath etc. right? How can I do that, haven't found anything in the docs.

**Comment by abbra** [comment]
IPA does not support moving the location of UI/RPC endpoints. There are quite a few places that expect it. We do not support sharing host with other applications.
Whatever you are designing to use here, most likely will not be supported.

**Comment by leonidas-o** [comment]
okay, I added the new host, deleted the freeipa volume and re-deployed it, also updated the ambassador mapping to:

```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: freeipa-ui
spec:
  host: freeipa.test.my.domain.com
  prefix: /
  rewrite: /
  service: http://freeipa-ui:80
  timeout_ms: 60000
  ...
```

but I'm getting `ERR_TOO_MANY_REDIRECTS` in the browser and in the freeipa access_log a lot of entries like:
```
...
[13/May/2022:11:41:32 +0000] "GET /ipa/ui HTTP/1.1" 301 254 "-" "Mozilla/5.0
...
```

**Comment by adelton** [comment]
It might be because the FreeIPA Apache HTTP Server's configuration expects those incoming connections to be via HTTPS on port 443, not via HTTP.

I've written about FreeIPA behind an SSL/TLS proxy in https://www.adelton.com/freeipa/freeipa-behind-ssl-proxy ... but it's been over six years ago, so the actual details might be a bit different, and it was not about containerized setups, so that might bring another variable to the equation. You might want to create such setup in plain VMs first and only then work on making it work in containers.

**Comment by leonidas-o** [comment]
Yes, had it finally working, It's the point you mentioned, it wants internally https. So the current `service.yaml` was updated to:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: freeipa-ui
spec:
  ports:
    - name: service-port
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: freeipa
  type: ClusterIP
  sessionAffinity: None
```

and the mapping to:
```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: freeipa-ui
spec:
  host: freeipa.test.my.domain.com
  prefix: /
  rewrite: /
  service: https://freeipa-ui:443
  timeout_ms: 60000
  ...
```

And the UI is now available. One thing which is different from a deploment in a VM, here via K8s, I'm getting a basic auth/ sign in window popping up, if I cancel that twice, I then get the regular login form. Why is that happening?
