### ISSUE TITLE
Failed to mount RPC Pipe File System

### ISSUE THREAD

**Issue by chanyshev** [freeipa/freeipa-container#459]
Hi
My docker-compose file
```
---
version: '3.7'
services:
  freeipa:
    image: localhost/freeipa-server-test-addons:centos-8-stream
    container_name: freeipa
    restart: unless-stopped
    hostname: freeipa.test.local
    environment:
      - IPA_SERVER_HOSTNAME=freeipa.test.local
      - PASSWORD=admin
      - oci-systemd-hook=disabled
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - freeipavol:/data:Z
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    command:
      - -U
      - --realm=test.local
      - --admin-password=admin
#      - --no-host-dns
#      - --unattended
    ports:
    # FreeIPA WebUI
      - "80:80"
      - "443:443"
    # Kerberos
      - "389:389"
      - "636:636"
      - "464:464"
      - "88:88/udp"
      - "464:464/udp"
    # NTP
      - "123:123/udp"
    # Other
      - "7389:7389"
      - "9443:9443"
      - "9444:9444"
      - "9445:9445"
    tmpfs:
      - /run
      - /tmp

volumes:
  freeipavol:
```
docker-compose logs
```
freeipa    | [  OK  ] Listening on Process Core Dump Socket.
freeipa    | [  OK  ] Reached target Local File Systems.
freeipa    |          Starting Rebuild Dynamic Linker Cache...
freeipa    | [  OK  ] Reached target Swap.
freeipa    | [  OK  ] Reached target Slices.
freeipa    | [  OK  ] Listening on initctl Compatibility Named Pipe.
freeipa    |          Starting Create System Users...
freeipa    |          Starting Mark the need to relabel after reboot...
freeipa    |          Starting Rebuild Journal Catalog...
freeipa    | [  OK  ] Listening on Journal Socket (/dev/log).
freeipa    |          Starting Journal Service...
freeipa    | [  OK  ] Reached target Network is Online.
freeipa    |          Starting Notify NFS peers of a restart...
freeipa    | [  OK  ] Started Dispatch Password Requests to Console Directory Watch.
freeipa    | [  OK  ] Reached target Paths.
freeipa    | [  OK  ] Listening on RPCbind Server Activation Socket.
freeipa    | [  OK  ] Reached target RPC Port Mapper.
freeipa    | [  OK  ] Started Read and set NIS domainname from /etc/sysconfig/network.
freeipa    | [  OK  ] Started Create System Users.
freeipa    | [  OK  ] Started Mark the need to relabel after reboot.
freeipa    | [  OK  ] Started Rebuild Journal Catalog.
freeipa    | [  OK  ] Started Notify NFS peers of a restart.
freeipa    | [  OK  ] Started Rebuild Dynamic Linker Cache.
freeipa    |          Starting Update is Completed...
freeipa    | [  OK  ] Started Update is Completed.
freeipa    | [  OK  ] Started Journal Service.
freeipa    |          Starting Flush Journal to Persistent Storage...
freeipa    | [  OK  ] Started Flush Journal to Persistent Storage.
freeipa    |          Starting Create Volatile Files and Directories...
freeipa    | [  OK  ] Started Create Volatile Files and Directories.
freeipa    |          Starting RPC Bind...
freeipa    |          Starting Update UTMP about System Boot/Shutdown...
freeipa    | [  OK  ] Started Update UTMP about System Boot/Shutdown.
freeipa    | [  OK  ] Reached target System Initialization.
freeipa    | [  OK  ] Started Daily Cleanup of Temporary Directories.
freeipa    | [  OK  ] Listening on D-Bus System Message Bus Socket.
freeipa    | [  OK  ] Reached target Sockets.
freeipa    | [  OK  ] Reached target Basic System.
freeipa    |          Starting GSSAPI Proxy Daemon...
freeipa    | [  OK  ] Started dnf makecache --timer.
freeipa    | [  OK  ] Reached target Timers.
freeipa    |          Starting System Security Services Daemon...
freeipa    | [  OK  ] Started D-Bus System Message Bus.
freeipa    | [  OK  ] Started GSSAPI Proxy Daemon.
freeipa    | [  OK  ] Started RPC Bind.
freeipa    | [  OK  ] Started System Security Services Daemon.
freeipa    | [  OK  ] Reached target User and Group Name Lookups.
freeipa    |          Mounting RPC Pipe File System...
freeipa    | [FAILED] Failed to mount RPC Pipe File System.
freeipa    | See 'systemctl status var-lib-nfs-rpc_pipefs.mount' for details.
freeipa    | [DEPEND] Dependency failed for rpc_pipefs.target.
freeipa    | [DEPEND] Dependency failed for RPC security service for NFS client and server.
freeipa    | [  OK  ] Reached target NFS client services.
freeipa    | [  OK  ] Reached target Remote File Systems (Pre).
freeipa    | [  OK  ] Reached target Remote File Systems.
freeipa    |          Starting Permit User Sessions...
freeipa    | [  OK  ] Started Permit User Sessions.
freeipa    | [  OK  ] Started Command Scheduler.
freeipa    | [  OK  ] Reached target Multi-User System.
freeipa    |          Starting Update UTMP about System Runlevel Changes...
freeipa    | [  OK  ] Started Update UTMP about System Runlevel Changes.
```
OS: Ubuntu 21.10
Docker version 20.10.14
docker-compose version 1.29.2
