### ISSUE TITLE
Failed to create /init.scope control group: Read-only file system

### ISSUE THREAD

**Issue by patsevanton** [freeipa/freeipa-container#510]
Hello! Thanks for freeipa. Great open source information management solution.

Get error:
```
[fedora@freeipa docker-compose]$ docker-compose up
[+] Running 2/2
 ⠿ Network docker-compose_default  Created                                                                                                                                                             0.1s
 ⠿ Container freeipa               Created                                                                                                                                                             0.4s
Attaching to freeipa
freeipa  | systemd 239 (239-67.el8) running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy)
freeipa  | Detected virtualization container-other.
freeipa  | Detected architecture x86-64.
freeipa  | Set hostname to <freeipa>.
freeipa  | Failed to create /init.scope control group: Read-only file system
freeipa  | Failed to allocate manager object: Read-only file system
freeipa  | [!!!!!!] Failed to allocate manager object, freezing.
freeipa  | Freezing execution.
```

docker-compose:
```
[fedora@freeipa docker-compose]$ cat docker-compose.yaml 
version: "3.8"

services:
  freeipa:
    image: freeipa/freeipa-server:centos-8-stream-4.9.10
    container_name: freeipa
    restart: unless-stopped
    hostname: freeipa
    domainname: freeipa.yyyyyy
    ports:
      - 123:123/udp
      - 389:389
      - 443:443
      - 464:464
      - 464:464/udp
#      - 53:53
#      - 53:53/udp
      - 636:636
      - 80:80
      - 88:88
      - 88:88/udp
    dns:
      - 1.1.1.1
    tty: true
    stdin_open: true
    environment:
      IPA_SERVER_HOSTNAME: freeipa.yyyyyyyyy
    command:
      - --admin-password=xxxxxxxxx
      - --allow-zone-overlap
      - --auto-forwarders
      - --dirsrv-pin=xxxxxxxxxxx
      - --domain=yyyyyyyy
      - --ds-password=xxxxxxxxx
      - --http-pin=xxxxxxxxxxxx
      - --no-dnssec-validation
      - --no-host-dns
      - --realm=yyyyyyy
      - --setup-dns
      - --unattended
      - -U
      - --external_cert_file=/freeipacert/certificate.crt
      - --external_ca_file=/ca/ca_cert.pem
    cap_add:
      - SYS_TIME
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/freeipa:/data
      - /etc/docker-compose/ca:/ca:ro
      - /etc/docker-compose/freeipacert:/freeipacert:ro
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
```

Info:
```
[fedora@freeipa docker-compose]$ tree
.
├── ca
│   ├── ca_cert.pem
│   ├── privkey.pem
│   └── request.csr
├── docker-compose.yaml
├── freeipacert
│   ├── certificate.crt
│   └── privkey.key
├── freeipa.packops.local.yaml
└── log

3 directories, 7 files
[fedora@freeipa docker-compose]$ pwd
/etc/docker-compose
[fedora@freeipa docker-compose]$ cat /etc/redhat-release 
Fedora release 35 (Thirty Five)
```
