### ISSUE TITLE
Can i Install freeipa with an external CA by one-stage ?

### ISSUE THREAD

**Issue by patsevanton** [freeipa/freeipa-container#511]
Hello! Thanks for FreeIPA!
Can i Install freeipa with an external CA by one-stage ?

I have CA and certificate for freeipa
```
ubuntu@freeipa:/etc/docker-compose$ tree
.
├── ca
│   ├── ca_cert.pem
│   ├── privkey.pem
├── docker-compose.yaml
├── freeipacert
│   ├── certificate.crt
│   └── privkey.key

3 directories, 7 files
```

docker-compose:
```
version: "3.8"

services:
  freeipa:
    image: freeipa/freeipa-server:centos-8-stream-4.9.10
    container_name: freeipa
    restart: unless-stopped
    hostname: freeipa
    domainname: freeipa.yyyyyy
    ports:
      - 123:123/udp
      - 389:389
      - 443:443
      - 464:464
      - 464:464/udp
#      - 53:53
#      - 53:53/udp
      - 636:636
      - 80:80
      - 88:88
      - 88:88/udp
    dns:
      - 1.1.1.1
    tty: true
    stdin_open: true
    environment:
      IPA_SERVER_HOSTNAME: freeipa.yyyyyyyyyy
    command:
      - --admin-password=xxxxxxxxx
      - --allow-zone-overlap
      - --auto-forwarders
      - --dirsrv-pin=xxxxxxxxxxxx
      - --domain=yyyyyyyyyy
      - --ds-password=xxxxxxxxxxxx
      - --http-pin=xxxxxxxxxxx
      - --no-dnssec-validation
      - --no-host-dns
      - --realm=yyyyyyyyyyy
      - --setup-dns
      - --unattended
      - -U
      - --external_cert_file=/freeipacert/certificate.crt
      - --external_ca_file=/ca/ca_cert.pem
    cap_add:
      - SYS_TIME
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/freeipa:/data
      - ./log:/var/logs
      - /etc/docker-compose/ca:/ca
      - /etc/docker-compose/freeipacert:/freeipacert
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
```

Get error:
```
freeipa  | CA is not installed yet. To install with an external CA is a two-stage process.
freeipa  | First run the installer with --external-ca.
freeipa  | The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```
