### ISSUE TITLE
cgroup2 / docker fails to bind ports

### ISSUE THREAD

**Issue by Luth1ng** [freeipa/freeipa-container#530]
Hello there,

I am using docker compose with the following configuration file : 

```
  freeipa:
    image: 'freeipa/freeipa-server:almalinux-9'
    container_name: freeipa-poc
    restart: always
    ports:
      - 10.0.3.159:4443:443
      - 10.0.3.159:4453:53
      - 10.0.3.159:4453:53/udp
      - 10.0.3.159:4480:80
      - 10.0.3.159:4389:389
      - 10.0.3.159:4636:636
      - 10.0.3.159:4488:88
      - 10.0.3.159:4488:88/udp
      - 10.0.3.159:4464:464
      - 10.0.3.159:4464:464/udp
      - 10.0.3.159:4123:123/udp
    dns:
      - 10.0.2.66
      - 10.0.1.34
      - 10.0.2.33
    environment:
      IPA_SERVER_HOSTNAME: ldap.test.local
      PASSWORD: Secret123
    volumes:
      - /apps/docker/data/freeipa/data:/data
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
```

When I run the container, for the first time, the installation suceeds without issue.
But, when I run the container afterwards, I got the following warning messages : 

```
docker compose run freeipa
systemd 250-12.el9_1.1 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization docker.
Detected architecture x86-64.
Queued start job for default target Minimal target for containerized FreeIPA server.
-.slice: Failed to get cgroup ID on cgroup /sys/fs/cgroup, ignoring: Operation not permitted
system.slice: Failed to get cgroup ID on cgroup /sys/fs/cgroup/system.slice, ignoring: Operation not permitted
nis-domainname.service: Failed to get cgroup ID on cgroup /sys/fs/cgroup/system.slice/nis-domainname.service, ignoring: Operation not permitted
systemd-journald.service: Failed to get cgroup ID on cgroup /sys/fs/cgroup/system.slice/systemd-journald.service, ignoring: Operation not permitted
system.slice: Failed to get cgroup ID on cgroup /sys/fs/cgroup/system.slice, ignoring: Operation not permitted
-.slice: Failed to get cgroup ID on cgroup /sys/fs/cgroup, ignoring: Operation not permitted
Tue May  9 07:34:46 UTC 2023 /usr/sbin/ipa-server-configure-first upgrade
FreeIPA server is already configured, starting the services.
Tue May  9 07:35:05 UTC 2023 /usr/sbin/ipa-server-configure-first update-self-ip-address
FreeIPA server does not run DNS server, skipping update-self-ip-address.
FreeIPA server started.
```

The container seems to be running without serious issue : 

```
docker compose ls
NAME                STATUS              CONFIG FILES
stack_pocsrvauth    running(1)          /apps/docker/data/docker-compose.yml

 docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS                                                                                          NAMES
94de61576a05   freeipa/freeipa-server:almalinux-9   "/usr/local/sbin/init"   29 seconds ago   Up 29 seconds   53/tcp, 80/tcp, 53/udp, 88/udp, 88/tcp, 389/tcp, 443/tcp, 123/udp, 464/tcp, 636/tcp, 464/udp   stack_pocsrvauth-freeipa-run-552e479bb989
```

However, as you can see, the ports aren't binded to the host.

My host is a debian 11 based, my system is a cgroupv2 : 
```
mount | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
```

and user namespace remapping is enabled : 
```
cat /etc/docker/daemon.json
{
   "data-root": "/apps/docker/root",
   "userns-remap": "default"
}
```

Many thanks for your help

**Comment by adelton** [comment]
Let's debug the issue completely outside of FreeIPA. Start with a Dockerfile
```
FROM docker.io/almalinux/9-minimal
RUN microdnf install -y httpd
ENTRYPOINT [ "/usr/sbin/httpd", "-DFOREGROUND" ]
```
and a docker-compose.yaml
```
version: '3.8'
services:
  www:
    build:
      context: .
    ports:
      - 10.0.3.159:4480:80
```

Now build the image with `docker-compose build`, and then run it the similar way you run the `freeipa` service:
```
$ docker-compose run www
Creating network "docker-compose-ports_default" with the default driver
Creating docker-compose-ports_www_run ... done
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.2. Set the 'ServerName' directive globally to suppress this message
```
and in another terminal
```
$ docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS          PORTS     NAMES
a2ea5fc280ed   docker-compose-ports_www   "/usr/sbin/httpd -DF…"   25 seconds ago   Up 24 seconds             docker-compose-ports_www_run_9d20780a97a6
```

Checking https://docs.docker.com/compose/compose-file/compose-file-v3/#ports I see a Note
> `docker-compose` run ignores ports unless you include `--service-ports`.

So I continue with
```
<Ctrl-C>
$ docker-compose run --service-ports www
Creating docker-compose-ports_www_run ... done
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.2. Set the 'ServerName' directive globally to suppress this message
```
and now in the other terminal I see
```
$ docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS         PORTS                     NAMES
bbe9273a3b19   docker-compose-ports_www   "/usr/sbin/httpd -DF…"   2 seconds ago   Up 2 seconds   10.0.3.159:4480->80/tcp   docker-compose-ports_www_run_484e6564932a
```
and I can also run
```
$ curl http://10.0.3.159:4480/
```
and get the Test Page for the HTTP Server on AlmaLinux HTML page from within the container on the expected port. (Well, obviously, I used different IP address but the rest is real.)

Is the `--service-ports` what was missing in your case, or is something else a problem?
