### ISSUE TITLE
snmp_collator_create_semaphore - Failed to create semaphore for stats file (/dev/shm/sem.slapd..) (Permission denied)

### ISSUE THREAD

**Issue by fsdrw08** [freeipa/freeipa-container#544]
host os: centos stream 9
container runtime: podman version: 4.4.1
description: I run deploy freeipa by command: `podman kube play`, below is the kube file
freeipa image tag: quay.io/freeipa/freeipa-server:centos-9-stream-4.10.2 (same error happen in 4.10.1)

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: freeipa
data:
  ipa-server-install-options: |
    --unattended

    --domain=infra.sololab
    --realm=infra.sololab
    --ds-password=P@ssw0rd
    --admin-password=P@ssw0rd

    --no-ntp
    --no_hbac_allow

    --setup-dns
    --no-host-dns
    --forwarder=192.168.255.1
    --auto-reverse

    --ip-address=192.168.255.11

    --debug
    --skip-mem-check
  ipa-ext.conf: |
    key "keySololab" {
            algorithm hmac-sha256;
            secret j/2DR2zkVAyDHL2XjE731sMt9s6cmRhXE6niScAgHA0=;
    };
---
apiVersion: v1
kind: Pod
metadata:
  name: freeipa
  labels:
    name: freeipa
spec:
  hostname: "ipa.infra.sololab"
  containers:
    - name: freeipa
      image: "quay.io/freeipa/freeipa-server:centos-9-stream-4.10.2"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "1336Mi"
          cpu: "1000m"
      ports:
        - name: dns_tcp
          containerPort: 53
          hostIP: "192.168.255.11"
          protocol: TCP
        - name: dns_udp
          hostIP: "192.168.255.11"
          containerPort: 53
          protocol: UDP

        - name: http
          containerPort: 80
          hostIP: "192.168.255.11"
          hostPort: 80
        - name: https
          containerPort: 443
          hostIP: "192.168.255.11"
          hostPort: 443
        - name: https-pki
          containerPort: 8443
          hostIP: "192.168.255.11"
          hostPort: 8443

        - name: ldap
          containerPort: 389
        - name: ldaps
          containerPort: 636

        - name: kerberos_tcp
          containerPort: 88
          protocol: TCP
        - name: kerberos_udp
          containerPort: 88
          protocol: UDP

        - name: kpasswd_tcp
          containerPort: 464
          protocol: TCP
        - name: kpasswd_udp
          containerPort: 464
          protocol: UDP
      env:
        - name: IPA_SERVER_HOSTNAME
          value: "ipa.infra.sololab"
      livenessProbe:
        initialDelaySeconds: 180
        periodSeconds: 60
        httpGet:
          path: /
          port: 80
      volumeMounts:
        - name: freeipa
          mountPath: /data
        - name: ipa-server-install-options
          mountPath: /data/ipa-server-install-options
          subPath: ipa-server-install-options
        - name: ipa-ext.conf
          mountPath: /etc/named/ipa-ext.conf
          subPath: ipa-ext.conf
        - name: dshm
          mountPath: /dev/shm
  volumes:
    - name: freeipa
      persistentVolumeClaim:
        claimName: freeipa
    - name: ipa-server-install-options
      configMap:
        name: freeipa
        items:
          - key: ipa-server-install-options
            path: ipa-server-install-options
    - name: ipa-ext.conf
      configMap:
        name: freeipa
        items:
          - key: ipa-ext.conf
            path: ipa-ext.conf
    # https://github.com/freeipa/freeipa-container/commit/024676573b6a59b4b361e35808f55739bd793e63
    - name: dshm
      emptyDir:
        medium: Memory
  dnsConfig:
    nameservers:
      - 127.0.0.1
  hostAliases:
    - ip: "192.168.255.11"
      hostnames:
        - "ipa.infra.sololab"
  restartPolicy: Never
```
error shows in `/var/log/ipaserver-install.log` :
```log
The ipa-server-install command failed, exception: CalledProcessError: Command '['systemctl', 'start', 'dirsrv@INFRA-SOLOLAB']' returned non-zero exit status 1.

Command '['systemctl', 'start', 'dirsrv@INFRA-SOLOLAB']' returned non-zero exit status 1.

The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```
error shows in `/var/log/dirsrv/slapd-REAML-NAME/errors`:
```log
        389-Directory/2.3.4 B2023.139.0000
        ipa.infra.sololab:389 (/etc/dirsrv/slapd-INFRA-SOLOLAB)

[30/Jun/2023:13:32:04.288976929 +0800] - INFO - main - 389-Directory/2.3.4 B2023.139.0000 starting up
[30/Jun/2023:13:32:04.292083007 +0800] - INFO - main - Setting the maximum file descriptor limit to: 1024
[30/Jun/2023:13:32:04.486993835 +0800] - INFO - PBKDF2_SHA256 - Based on CPU performance, chose 2048 rounds
[30/Jun/2023:13:32:04.494388230 +0800] - INFO - bdb_config_upgrade_dse_info - create config entry from old config
[30/Jun/2023:13:32:04.499861588 +0800] - NOTICE - bdb_start_autotune - found 1752984k physical memory
[30/Jun/2023:13:32:04.502128584 +0800] - NOTICE - bdb_start_autotune - found 816256k available
[30/Jun/2023:13:32:04.503900122 +0800] - NOTICE - bdb_start_autotune - cache autosizing: db cache: 109561k
[30/Jun/2023:13:32:04.505907445 +0800] - NOTICE - bdb_start_autotune - total cache size: 89752780 B;
[30/Jun/2023:13:32:04.710930250 +0800] - INFO - connection_table_new - Number of connection sub-tables 1, each containing 960 slots.
[30/Jun/2023:13:32:04.718368265 +0800] - EMERG - snmp_collator_create_semaphore - Failed to create semaphore for stats file (/dev/shm/sem.slapd-INFRA-SOLOLAB.stats). Error 13.(Permission denied)
```
