### ISSUE TITLE
kdcproxy failed to start

### ISSUE THREAD

**Issue by rskvp93** [freeipa/freeipa-container#551]
kdcproxy works by running an application wsgi group process under the `kdcproxy` user. 

Apache2 config:
```
WSGIDaemonProcess kdcproxy processes=1 threads=1 maximum-requests=5000 \
  user=kdcproxy group=kdcproxy display-name=%{GROUP}
WSGIScriptAlias /KdcProxy /usr/share/ipa/kdcproxy.wsgi \
  process-group=kdcproxy application-group=%{GLOBAL}
WSGIScriptReloading Off

<Location "/KdcProxy">
  Satisfy Any
  Require all granted
</Location>
```

But the home directory of the kdcproxy user - `/var/lib/kdcproxy`  was not created at installing time. So the apache2 can not start the kdcproxy wsgi application group process. It raises many errors in error_log file.

```
[root@ipa01 /]# tail /var/log/httpd/error_log 
[Thu Aug 10 08:05:24.675766 2023] [wsgi:alert] [pid 162742:tid 162742] (2)No such file or directory: mod_wsgi (pid=162742): Unable to change working directory to home directory '/var/lib/kdcproxy' for uid=288.
[Thu Aug 10 08:05:24.675796 2023] [wsgi:alert] [pid 162742:tid 162742] mod_wsgi (pid=162742): Failure to configure the daemon process correctly and process left in unspecified state. Restarting daemon process after delay.
[Thu Aug 10 08:05:44.696639 2023] [wsgi:alert] [pid 162926:tid 162926] (2)No such file or directory: mod_wsgi (pid=162926): Unable to change working directory to home directory '/var/lib/kdcproxy' for uid=288.
[Thu Aug 10 08:05:44.696669 2023] [wsgi:alert] [pid 162926:tid 162926] mod_wsgi (pid=162926): Failure to configure the daemon process correctly and process left in unspecified state. Restarting daemon process after delay.
```
```
[root@ipa01 /]# ls -lah /var/lib/kdcproxy
ls: cannot access '/var/lib/kdcproxy': No such file or directory
```

**Comment by abbra** [comment]
This folder, `/var/lib/kdcproxy`, is a part of `freeipa-server-common` package. It should be installed when the package is installed.

**Comment by rskvp93** [comment]
I tested on the lastest `Dockerfile.almalinux-9` version

```
[root@ipa01 /]# repoquery -l ipa-server-common.noarch|grep kdcproxy
Last metadata expiration check: 0:02:22 ago on Thu Aug 10 08:20:13 2023.
/etc/ipa/kdcproxy
/etc/ipa/kdcproxy/ipa-kdc-proxy.conf
/etc/ipa/kdcproxy/kdcproxy.conf
/usr/share/ipa/kdcproxy-disable.uldif
/usr/share/ipa/kdcproxy-enable.uldif
/usr/share/ipa/kdcproxy.wsgi
/var/lib/kdcproxy
```

The standard package has `/var/lib/kdcproxy` but I still don't know why this folder was disappear.

**Comment by abbra** [comment]
Perhaps, `/var/lib` (or `/var`) is a volume that is overridden in your environment? This would be pretty much dramatic to IPA server execution.

**Comment by rskvp93** [comment]
I think I don't override `/var` folder. This is my docker-compose.yaml
```
version: "3"

services:
  freeipa-almalinux9:
    build:
      context: .
      dockerfile: Dockerfile.almalinux-9
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    container_name: freeipa-server-almalinux9
    hostname: ipa01.lab.local
    network_mode: bridge
    user: root
    stdin_open: true 
    tty: true
    # privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 80:80/tcp
      - 443:443/tcp
      - 389:389/tcp
      - 636:636/tcp
      - 88:88/tcp
      - 464:464/tcp
      - 88:88/udp
      - 464:464/udp
      - 123:123/udp
    environment:
      - IPA_SERVER_IP=192.168.2.138
    volumes:
      - ./data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
```
And I run the following command to install freeipa: 
```
docker-compose run freeipa-almalinux9 -r lab.local --ds-password xxxxxxx --admin-password xxxxxx --setup-dns --ip-address 192.168.2.138 --allow-zone-overlap
```

Could you take a look into it?
