### ISSUE TITLE
Installing freeIPA with external CA

### ISSUE THREAD

**Issue by basanys** [freeipa/freeipa-container#567]
I am following this guide from [redhat documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/installing_identity_management/installing-an-ipa-server-with-external-ca_installing-identity-management) to install freeIPA with external CA.

I am using docker and here is my docker-compose file,
```
version: '3.3'
services:
  freeipa:
    image: freeipa/freeipa-server:almalinux-9-4.10.1
    #restart: always
    hostname: testfreeipa.test.lan
    command:
      - ipa-server-install
      - --hostname=testfreeipa.test.lan
      - --realm=TEST.LAN
      - --domain=test.lan
      - --ds-password=secret
      - --admin-password=secret
      - --external-ca
      - --no-host-dns
      - --unattended
    volumes:
      - ./freeipa:/data
      - /root/certs/:/root/certs/
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    ports:
      - 80:80
      - 443:443
      # Lot of ports
```
 The process involves two stages, first stage freeIPA generates CSR and second stage to submit certificates and CA.
 The problem is container exits after first stage with following output.
```
 ......
 freeipa_1  | Done configuring Kerberos KDC (krb5kdc).
freeipa_1  | Configuring kadmin
freeipa_1  |   [1/2]: starting kadmin
freeipa_1  |   [2/2]: configuring kadmin to start on boot
freeipa_1  | Done configuring kadmin.
freeipa_1  | Configuring ipa-custodia
freeipa_1  |   [1/5]: Making sure custodia container exists
freeipa_1  |   [2/5]: Generating ipa-custodia config file
freeipa_1  |   [3/5]: Generating ipa-custodia keys
freeipa_1  |   [4/5]: starting ipa-custodia
freeipa_1  |   [5/5]: configuring ipa-custodia to start on boot
freeipa_1  | Done configuring ipa-custodia.
freeipa_1  | Configuring certificate server (pki-tomcatd). Estimated time: 3 minutes
freeipa_1  |   [1/15]: configuring certificate server instance
freeipa_1  | The next step is to get /root/ipa.csr signed by your CA and re-run /usr/sbin/ipa-server-install as:
freeipa_1  | /usr/sbin/ipa-server-install --external-cert-file=/path/to/signed_certificate --external-cert-file=/path/to/external_ca_certificate
freeipa_1  | FreeIPA CA CSR stored in file ipa.csr located in bind-mounted data volume.
freeipa_1  | Failed to set wall message, ignoring: Could not activate remote peer.
freeipa_1  | Call to PowerOff failed: Could not activate remote peer.
root_freeipa_1 exited with code 0
```

How to submit the signed certificates in second stage if container exits in first stage? 
First stage ipa-server-install command is successful, but it exists. Here is ipaserver-install.log

```
...
2023-11-06T13:47:20Z DEBUG Keep pkispawn files for step 2
2023-11-06T13:47:20Z INFO The ipa-server-install command was successful
```
