### ISSUE TITLE
client containers only for old distros

### ISSUE THREAD

**Issue by daniejstriata** [freeipa/freeipa-container#599]
When looking at the branches for clients it seems there are only clients for RHEL/Centos7 and Fed22. Can I use these on modern distros like Centos 9 stream?

**Comment by adelton** [comment]
You can try but you are likely the first person to try after ages.

The problem is -- you typically want the client container to IPA enroll (if it's not yet) *and* do something useful, not just run `ipa-client-install` and then linger in an infinite loop. You could argue that you can `docker exec` to that container and do something with it but the typical workflow with `docker-compose` or in Kubernetes does not use that approach.

You might want to check https://github.com/adelton/webauthinfra where the IdP, web server, and client containers run the `ipa-client-enroll.service` and then also run the rest of the useful activity in subsequent systemd services.

Well, perhaps even that should be changed to use the `condition: service_completed_successfully`, the docker-compose's equivalent of `initContainers`, although https://github.com/compose-spec/compose-spec/issues/144 is still open so who knows how standard it is?

Or a full sidecar SSSD container? That might have the benefit that the systemd for SSSD would only be needed in that sidecar, not in the main application container. But then we'd need to properly ensure the volumes with pipes / sockets are shared, and keep up with any changes that might happen in newer versions of `ipa-client-install` and SSSD and perhaps other components.

Maybe it's time we removed the mention of the client branches from the README altogether, to avoid confusing people. @abbra Would you know if there is some general-usage solution for the client side similar to https://github.com/SSSD/sssd-ci-containers (which is designated for development and testing of SSSD only), to point people to instead?

**Comment by adelton** [comment]
Note to self:
```
services:
    db:
        image: busybox
        command: sh -c 'date ; echo I am a db. && sleep 30'
    init-db:
        image: busybox
        command: sh -c 'date ; echo I am the init db. && sleep 5 && date && echo Now I exit.'
        depends_on:
            db:
                condition: service_started
    app:
        image: busybox
        command: sh -c 'date && echo I am an app. && sleep 5 && date && echo I now exit.'
        depends_on:
            init-db:
                condition: service_completed_successfully
```
works as expected (`app` only starts after `init-db` finishes) with docker-compose-1.29.2-10.fc39.noarch even if the output does not start flowing until the `init-db` container finishes:
```
$ docker-compose up
Creating network "dc3_default" with the default driver
Creating dc3_db_1 ... done
Creating dc3_init-db_1 ... done
Creating dc3_app_1     ... done
Attaching to dc3_db_1, dc3_init-db_1, dc3_app_1
app_1      | Thu Mar 14 09:03:15 UTC 2024
app_1      | I am an app.
db_1       | Thu Mar 14 09:03:09 UTC 2024
db_1       | I am a db.
init-db_1  | Thu Mar 14 09:03:09 UTC 2024
init-db_1  | I am the init db.
init-db_1  | Thu Mar 14 09:03:14 UTC 2024
init-db_1  | Now I exit.
dc3_init-db_1 exited with code 0
app_1      | Thu Mar 14 09:03:20 UTC 2024
app_1      | I now exit.
dc3_app_1 exited with code 0
dc3_db_1 exited with code 0
```
