### ISSUE TITLE
docker compose always starts install

### ISSUE THREAD

**Issue by crosenbe** [freeipa/freeipa-container#622]
I started the container a first time to configure it and switched to compose later on. Starting the container with "docker run" still works, but not with compose. /data is the same volume, it seems there are no differences.

```
volumes:
  freeipa-data:

services:
  server:
    image: freeipa/freeipa-server:almalinux-9
    container_name: freeipa
    hostname: ipa.foo.bar
    tty: true
    stdin_open: true
    environment:
      IPA_SERVER_HOSTNAME: ipa.foo.bar
      TZ: "Europe/Paris"
    read_only: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    cgroup: host
    restart: always
    cap_add:
      - SYS_TIME
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup/freeipa.scope:/sys/fs/cgroup
      - freeipa-data:/data:Z
    ports:
      - "53:53/udp"
      - "53:53"
      - "80:80"
      - "10443:443"
      - "389:389"
      - "636:636"
      - "88:88/udp"
      - "88:88"
      - "464:464/udp"
      - "464:464"
      - "123:123/udp"
    security_opt:
      - "seccomp:unconfined"

```
