### ISSUE TITLE
Not able to open Web UI through host ip address

### ISSUE THREAD

**Issue by GitHanter** [freeipa/freeipa-container#629]
I started the container using following `compose.yml`

```yml
services:
  freeipa:
    hostname: ipa.example.com
    image: freeipa/freeipa-server:fedora-40
    container_name: freeipa-server
    restart: unless-stopped
    cgroup: host
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "0"
    command: 
      - ipa-server-install 
      - --realm=example.com
      - --domain=example.com
      - --ds-password=DirectoryManagerPassword  
      - --admin-password=admin_password
      - --no-host-dns 
      - --no-ntp 
      - --unattended
      - -U
    ports:
     - "389:389"
     - "636:636"
     - "88:88/udp"
     - "88:88/tcp"
     - "464:464/udp"
     - "464:464/tcp"
     - "180:80"
     - "1443:443"
    volumes:
       - ./ipa-data:/data:Z
       - /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service:/sys/fs/cgroup:rw
    environment:
      - IPA_SERVER_IP=10.20.65.5
    extra_hosts:
      - "ipa.example.com:10.20.65.5"
    networks:
      ipa:
        ipv4_address: 10.20.65.5
    cap_add:
      - SYS_TIME

networks:
  ipa:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1300
    ipam:
      config:
        - subnet: "10.20.65.0/24"
```

my host ip address is `192.168.1.100`, I want to access the web ui though `http://192.168.1.100:180` or `https://192.168.1.100:1443`, but it always redirect me to `https://ipa.example.com`

I check the `ipa-data/etc/httpd/conf.d/ipa-rewrite.conf`, content as following

```conf
# VERSION 7 - DO NOT REMOVE THIS LINE

RewriteEngine on

# By default forward all requests to /ipa. If you don't want IPA
# to be the default on your web server comment this line out.
RewriteRule ^/$ https://ipa.example.com/ipa/ui [L,NC,R=301]

# Redirect to the fully-qualified hostname. Not redirecting to secure
# port so configuration files can be retrieved without requiring SSL.
RewriteCond %{HTTP_HOST}    !^ipa.example.com$ [NC]
RewriteCond %{HTTP_HOST}    !^ipa-ca.example.com$ [NC]
RewriteRule ^/ipa/(.*)      http://ipa.example.com/ipa/$1 [L,R=301]

# Redirect to the secure port if not displaying an error or retrieving
# configuration.
RewriteCond %{SERVER_PORT}  !^443$
RewriteCond %{REQUEST_URI}  !^/ipa/(errors|config|crl)
RewriteCond %{REQUEST_URI}  !^/ipa/[^\?]+(\.js|\.css|\.png|\.gif|\.ico|\.woff|\.svg|\.ttf|\.eot)$
RewriteRule ^/ipa/(.*)      https://ipa.example.com/ipa/$1 [L,R=301,NC]

RewriteCond %{HTTP_HOST}    ^ipa-ca.example.com$ [NC]
RewriteCond %{REQUEST_URI}  !^/ipa/crl
RewriteCond %{REQUEST_URI}  !^/(ca|kra|pki|acme)
RewriteRule ^/(.*)          https://ipa.example.com/$1 [L,R=301]

# Rewrite for plugin index, make it like it's a static file
RewriteRule ^/ipa/ui/js/freeipa/plugins.js$    /ipa/wsgi/plugins.py [PT]
```

I want to know how to config so that I can access the `ipa services`(Directory, Web UI) through host ip address, just like many other apps running in docker container
