### ISSUE TITLE
More upgrade path tests needed

### ISSUE THREAD

**Issue by adelton** [freeipa/freeipa-container#664]
Currently https://github.com/freeipa/freeipa-container/blob/master/.github/build-test-params.yaml defines the upgrade matrix as
```
  upgrade-to-from:
    fedora-rawhide:
      - fedora-41
    fedora-41:
      - fedora-41
      - fedora-40
    fedora-40:
      - fedora-40
      - fedora-39
    almalinux-8:
      - centos-8-certs-updated-data
    rocky-8:
      - centos-8-certs-updated-data
```

That means we don't test upgrades for the RHEL 9-derived installations, nor upgrades from RHEL 8-based to RHEL 9 and from RHEL 9 to CentOS 10 Stream.

We should produce and push more `data-*` images with various installations to https://quay.io/repository/freeipa/freeipa-server?tab=tags, test what works, and extend the `test-upgrade` matrix.
