### ISSUE TITLE
Missing log directories when /var/log is a volume and /etc is read-only

### ISSUE THREAD

**Issue by DaAwesomeP** [freeipa/freeipa-container#675]
Hello,

I'm seeing an issue where maybe there should be a `mkdir -p /var/log/pki` or maybe we can add a note to the README about mounts for logs when `read_only: true`.

Here are the mounts that I needed:
```yaml
read_only: true
volumes:
  - ./ipa-data:/data:Z
  - ./log:/var/log

  # this directory must be in the container but is missing when mounting an empty volume
  # Docker creates this directory when mounting (by default)
  - ./log/pki:/var/log/pki

  # this directory is not writable when read-only
  - ./etc/httpd/logs/:/etc/httpd/logs
```
