### ISSUE TITLE
Use hostname command instead of $HOSTNAME

### ISSUE THREAD

**Issue by JoyceBabu** [freeipa/freeipa-container#98]
When using `docker-compose`, the $HOSTNAME variable is not updated correctly. Please use `hostname -f` command instead of $HOSTNAME for detecting hostname in init-data

https://github.com/docker/compose/issues/4217

**Comment by JoyceBabu** [comment]
I just saw the related ticket https://github.com/adelton/docker-freeipa/issues/89

**Comment by JoyceBabu** [comment]
I tried to work around the issue by setting `HOSTNAME=freeipa.example.com` environment variable in my `docker-compose.yml`.

`hostname -f` outputs `freeipa.example.com` inside `/usr/local/sbin/init`. But once `/usr/sbin/init` is started, it is reset to `example.com`.

**Comment by mmarzantowicz** [comment]
Put `hostname: FQDN.GOES.HERE` in `docker-compose.yml` under your container definition, this works for me. I don't use `HOSTNAME` variable.

**Comment by JoyceBabu** [comment]
I had tried that, but that too did not work.

The `docker run -h FQDN` option works correctly, but the `hostname` key in `docker-compose.yml` does not yield the same result.

**Comment by mmarzantowicz** [comment]
According to your first post, you're using `hostname` with `domainname`. What about using only one of them (`hostname`)?

Please also consider posting here detailed versions of software, you are using.

**Comment by JoyceBabu** [comment]
For the past three days, I have been trying to get the freeipa image
working with docker-compose. I have run into lots of issues.

I had tried using the hostname option alone (without domainname key) too.
But the result was the same.

I am using the latest docker version on Ubuntu. I don't have access to the
machine right now. I will post the exact version information soon.

Can you please confirm if the docker-compose.yml I posted above is working
for you?

**Comment by JoyceBabu** [comment]
Software version details

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64


$ docker-compose version
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

**Comment by JoyceBabu** [comment]
I have updated docker-compose to 1.9. Now the `$HOSTNAME` variable shows `freeipa`. The container hostname is still incorrect.

```
[root@example /]# echo $HOSTNAME
freeipa
[root@example /]# hostname
example.com
[root@example /]# hostname -f
hostname: No address associated with hostname
[root@example /]# hostname -s
example
[root@example /]# hostname -d
hostname: No address associated with hostname
[root@example /]# 
```
My `docker-compose.yml`

```yml
version: "2"
services:
    freeipa:
        container_name: freeipa
        image: adelton/freeipa-server:fedora-25
        restart: always
        hostname: freeipa.example.com
        #domainname: example.com
        environment:
            #- HOSTNAME=freeipa.example.com
            - IPA_SERVER_IP=10.10.0.106
            - IPA_SERVER_HOSTNAME=freeipa.example.com
        volumes:
            - ./data/:/data:Z
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        networks:
            net-external:
                ipv4_address: "10.10.0.106"
        tty: true
        stdin_open: true
        cap_add:
            - SYS_ADMIN
        security_opt:
            - "seccomp:unconfined"
        command:  --domain=example.com --realm=example.com --http-pin=testpass --dirsrv-pin=testpass --ds-password=testpass --admin-password=testpass -U --no-host-dns --no-dnssec-validation --setup-dns --auto-forwarders --allow-zone-overlap --unattended

networks:
    net-external:
      external: true
```
