### ISSUE TITLE
Services automatically exits and container loses internet access when restarted

### ISSUE THREAD

**Issue by JoyceBabu** [freeipa/freeipa-container#99]
When the `--setup-dns` option is used, the services does not stay running on restarting the container.

**docker-compose.yml**
```yml
version: "2"
services:
    freeipa:
        container_name: freeipa
        image: adelton/freeipa-server:fedora-25
        restart: always
        hostname: freeipa
        domainname: example.com
        environment:
            - HOSTNAME=freeipa.example.com
            - IPA_SERVER_IP=10.10.0.106
            - IPA_SERVER_HOSTNAME=freeipa.example.com
        volumes:
            - ./data/:/data:Z
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        networks:
            net-external:
                ipv4_address: "10.10.0.106"
        tty: true
        stdin_open: true
        cap_add:
            - SYS_ADMIN
        security_opt:
            - "seccomp:unconfined"
        command:  --domain=example.com --realm=example.com --http-pin=testpass --dirsrv-pin=testpass --ds-password=testpass --admin-password=testpass -U --no-host-dns --no-dnssec-validation --setup-dns --auto-forwarders --allow-zone-overlap --unattended

networks:
    net-external:
      external: true
```

The container is working fine when I run `docker-compose up`.

But if I do `docker-compose stop && docker-compose up`, then the services running inside the container automatically exits a few seconds after the container is restarted.
